### ISSUE TITLE
Not deploying endpoints for all services

### ISSUE THREAD

**Issue by ryanbas21** [okteto/okteto#2715]
**Describe the bug**
I am deploying 5 services via docker-compose, and they appear to mostly deploy successfully. However, I only get 2 endpoints, when there should be 5.

**To Reproduce**
I don't really know how to reproduce it as its the only result of the build I have. 
![Screen Shot 2022-05-24 at 2 31 13 PM](https://user-images.githubusercontent.com/18267769/170126723-c14681e5-dbf3-4fc1-9dd4-6c6e08a71580.png)

**Expected behavior**
I would expect that I have 5 endpoints if I have 5 services.

Of note, I have an issue open on the community [forum](https://community.okteto.com/t/error-in-finishpipeline-label-name-name-missing-in-label-map/91/3) that shows an error I get after all the endpoints are "deployed". So i'm not sure if this error is related.

**Comment by ryanbas21** [comment]
Hi @jLopezbarb I am using the okteto CLI 2.3.1. The master branch wouldn't be the proper branch to test this on. https://github.com/ForgeRock/forgerock-javascript-sdk/pull/244 is what i've been developing on and where i experience the issue. Why would the react service cause two backend services which aren't directly related to not deploy endpoints?

**Comment by jLopezbarb** [comment]
@ryanbas21 we found the issue and it's now fixed on cloud, can you try redeploying the preview env again?

Also, we noticed that you are still using a manifest v1. Check it out our [new manifest v2](https://www.okteto.com/docs/reference/manifest-migration/). This will simplify all your okteto manifests into one, simplify your pipeline by using the build section, and allows you to develop on several services by declaring them on the dev section!!

**Comment by ryanbas21** [comment]
Awesome! Will redeploy probably tommorow!

**Comment by jmacelroy** [comment]
The two issues found have been fixed. @ryanbas21 let us know if you continue to have issues.

**Comment by ryanbas21** [comment]
@jmacelroy I deployed today and i have the same issue.

<img width="800" alt="Screen Shot 2022-06-28 at 11 21 49 AM" src="https://user-images.githubusercontent.com/18267769/176244554-1610fb76-c7e6-4d82-a1eb-125a5a04226f.png">
<img width="564" alt="Screen Shot 2022-06-28 at 11 22 51 AM" src="https://user-images.githubusercontent.com/18267769/176244557-153fada3-c15f-49dd-bbba-b5ed52cb89c1.png">


The todo api is not being assigned a url.

**Comment by jmacelroy** [comment]
@jLopezbarb can you take a look at this one. I think in the original report there were two bugs that we fixed but either we didn't fix one of them or there's a third issue here.

**Comment by jLopezbarb** [comment]
Hi @ryanbas21, 
`todo-api` is not creating an endpoint because the port is no longer exposed:
<img width="455" alt="Captura de pantalla 2022-06-29 a las 10 10 40" src="https://user-images.githubusercontent.com/25170843/176386026-49861d12-0507-4901-9089-11f3fc6dbfc4.png">

If you want to make the service public you'll need to set the host on the ports like this:
``` yaml
services:
  todo-api:
     container_name: todo-api
     build:
       context: ./
       dockerfile: ./Dockerfile
     command: node /app/builder/dist/samples/todo-api/main.js
     ports:
       - 8081:8081
```
